# Form implementation generated from reading ui file 'choice.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Platform(object):
    def setupUi(self, Platform):
        Platform.setObjectName("Platform")
        Platform.resize(1124, 724)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resource/icon.png"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        Platform.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Platform)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_panel = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_panel.sizePolicy().hasHeightForWidth())
        self.left_panel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 63, 138))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.left_panel.setPalette(palette)
        self.left_panel.setAutoFillBackground(False)
        self.left_panel.setStyleSheet("QFrame {\n"
                                      "background-color: #173F8A;\n"
                                      "}")
        self.left_panel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.left_panel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.left_panel)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.left_panel)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.right_panel = QtWidgets.QFrame(parent=self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_panel.sizePolicy().hasHeightForWidth())
        self.right_panel.setSizePolicy(sizePolicy)
        self.right_panel.setAutoFillBackground(False)
        self.right_panel.setStyleSheet("QFrame {\n"
                                       "background-color: #ffffff;\n"
                                       "}")
        self.right_panel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.right_panel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.right_panel)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.stats_label = QtWidgets.QLabel(parent=self.right_panel)
        self.stats_label.setStyleSheet("color: #2c5282;\n"
                                       "font-size: 12px;\n"
                                       "margin: 5px;\n"
                                       "padding: 8px;\n"
                                       "background-color: #e2e8f0;\n"
                                       "border-radius: 5px;")
        self.stats_label.setObjectName("stats_label")
        self.verticalLayout_2.addWidget(self.stats_label)
        self.file_list = QtWidgets.QListWidget(parent=self.right_panel)
        self.file_list.setStyleSheet("QListWidget {\n"
                                     "                background-color: white;\n"
                                     "                color: #1a202c;\n"
                                     "                border: 2px solid #3182ce;\n"
                                     "                border-radius: 8px;\n"
                                     "                font-size: 13px;\n"
                                     "                font-family: Consolas;\n"
                                     "            }\n"
                                     " QListWidget::item {\n"
                                     "                padding: 10px;\n"
                                     "                border-bottom: 1px solid #e2e8f0;\n"
                                     "            }\n"
                                     "QListWidget::item:selected {\n"
                                     "                background-color: #3182ce;\n"
                                     "                color: white;\n"
                                     "                border-radius: 5px;\n"
                                     "            }")
        self.file_list.setObjectName("file_list")
        self.verticalLayout_2.addWidget(self.file_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_button = QtWidgets.QPushButton(parent=self.right_panel)
        self.add_button.setStyleSheet("QPushButton {\n"
                                      "                    background-color: #48bb78;\n"
                                      "                    color: white;\n"
                                      "                    border: none;\n"
                                      "                    padding: 10px 15px;\n"
                                      "                    border-radius: 6px;\n"
                                      "                    font-weight: bold;\n"
                                      "                    font-size: 12px;\n"
                                      "                }\n"
                                      "QPushButton:hover {\n"
                                      "                    background-color: #3c9e65;\n"
                                      "                }\n"
                                      "QPushButton:pressed {\n"
                                      "                    background-color: #286a43;\n"
                                      "                }")
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.add_button)
        self.open_button = QtWidgets.QPushButton(parent=self.right_panel)
        self.open_button.setStyleSheet("QPushButton {\n"
                                       "                    background-color: #3182ce;\n"
                                       "                    color: white;\n"
                                       "                    border: none;\n"
                                       "                    padding: 10px 15px;\n"
                                       "                    border-radius: 6px;\n"
                                       "                    font-weight: bold;\n"
                                       "                    font-size: 12px;\n"
                                       "                }\n"
                                       "QPushButton:hover {\n"
                                       "                    background-color: rgb(37, 100, 159);\n"
                                       "                }\n"
                                       "QPushButton:pressed {\n"
                                       "                    background-color: rgb(25, 68, 109);\n"
                                       "                }")
        self.open_button.setObjectName("open_button")
        self.horizontalLayout_2.addWidget(self.open_button)
        self.delete_button = QtWidgets.QPushButton(parent=self.right_panel)
        self.delete_button.setStyleSheet("QPushButton {\n"
                                         "                    background-color: #ed8936;\n"
                                         "                    color: white;\n"
                                         "                    border: none;\n"
                                         "                    padding: 10px 15px;\n"
                                         "                    border-radius: 6px;\n"
                                         "                    font-weight: bold;\n"
                                         "                    font-size: 12px;\n"
                                         "                }\n"
                                         "QPushButton:hover {\n"
                                         "                    background-color: rgb(195, 112, 44);\n"
                                         "                }\n"
                                         "QPushButton:pressed {\n"
                                         "                    background-color: rgb(176, 101, 40);\n"
                                         "                }")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.update_button = QtWidgets.QPushButton(parent=self.right_panel)
        self.update_button.setStyleSheet("QPushButton {\n"
                                         "                    background-color: rgb(170, 85, 255);\n"
                                         "                    color: white;\n"
                                         "                    border: none;\n"
                                         "                    padding: 10px 15px;\n"
                                         "                    border-radius: 6px;\n"
                                         "                    font-weight: bold;\n"
                                         "                    font-size: 12px;\n"
                                         "                }\n"
                                         "QPushButton:hover {\n"
                                         "                    background-color: rgb(121, 0, 182);\n"
                                         "                }\n"
                                         "QPushButton:pressed {\n"
                                         "                    background-color: rgb(117, 0, 176);\n"
                                         "                }")
        self.update_button.setObjectName("update_button")
        self.horizontalLayout_2.addWidget(self.update_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.right_panel)
        self.stackedWidget.addWidget(self.main_page)
        self.analysis_page = QtWidgets.QWidget()
        self.analysis_page.setObjectName("analysis_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.analysis_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.analysis_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame {\n"
                                 "    background-color: #ffffff;\n"
                                 "    border-radius: 10px;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.preprocessing_button = QtWidgets.QPushButton(parent=self.frame)
        self.preprocessing_button.setMinimumSize(QtCore.QSize(200, 120))
        self.preprocessing_button.setStyleSheet("QPushButton {\n"
                                                "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                "                                stop: 0 #4CAF50, stop: 1 #45a049);\n"
                                                "    color: white;\n"
                                                "    border: none;\n"
                                                "    border-radius: 15px;\n"
                                                "    font-weight: bold;\n"
                                                "    font-size: 16px;\n"
                                                "    padding: 20px;\n"
                                                "}\n"
                                                "QPushButton:hover {\n"
                                                "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                "                                stop: 0 #45a049, stop: 1 #3d8b40);\n"
                                                "}\n"
                                                "QPushButton:pressed {\n"
                                                "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                "                                stop: 0 #3d8b40, stop: 1 #357c38);\n"
                                                "}")
        self.preprocessing_button.setObjectName("preprocessing_button")
        self.gridLayout.addWidget(self.preprocessing_button, 0, 0, 1, 1)
        self.visualization_button = QtWidgets.QPushButton(parent=self.frame)
        self.visualization_button.setMinimumSize(QtCore.QSize(200, 120))
        self.visualization_button.setStyleSheet("QPushButton {\n"
                                                "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                "                                stop: 0 #2196F3, stop: 1 #1976D2);\n"
                                                "    color: white;\n"
                                                "    border: none;\n"
                                                "    border-radius: 15px;\n"
                                                "    font-weight: bold;\n"
                                                "    font-size: 16px;\n"
                                                "    padding: 20px;\n"
                                                "}\n"
                                                "QPushButton:hover {\n"
                                                "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                "                                stop: 0 #1976D2, stop: 1 #1565C0);\n"
                                                "}\n"
                                                "QPushButton:pressed {\n"
                                                "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                                "                                stop: 0 #1565C0, stop: 1 #0D47A1);\n"
                                                "}")
        self.visualization_button.setObjectName("visualization_button")
        self.gridLayout.addWidget(self.visualization_button, 0, 1, 1, 1)
        self.modeling_button = QtWidgets.QPushButton(parent=self.frame)
        self.modeling_button.setMinimumSize(QtCore.QSize(200, 120))
        self.modeling_button.setStyleSheet("QPushButton {\n"
                                           "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                           "                                stop: 0 #FF9800, stop: 1 #F57C00);\n"
                                           "    color: white;\n"
                                           "    border: none;\n"
                                           "    border-radius: 15px;\n"
                                           "    font-weight: bold;\n"
                                           "    font-size: 16px;\n"
                                           "    padding: 20px;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                           "                                stop: 0 #F57C00, stop: 1 #EF6C00);\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                           "                                stop: 0 #EF6C00, stop: 1 #E65100);\n"
                                           "}")
        self.modeling_button.setObjectName("modeling_button")
        self.gridLayout.addWidget(self.modeling_button, 1, 0, 1, 1)
        self.back_button = QtWidgets.QPushButton(parent=self.frame)
        self.back_button.setMinimumSize(QtCore.QSize(200, 120))
        self.back_button.setStyleSheet("QPushButton {\n"
                                       "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                       "                                stop: 0 #9C27B0, stop: 1 #7B1FA2);\n"
                                       "    color: white;\n"
                                       "    border: none;\n"
                                       "    border-radius: 15px;\n"
                                       "    font-weight: bold;\n"
                                       "    font-size: 16px;\n"
                                       "    padding: 20px;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                       "                                stop: 0 #7B1FA2, stop: 1 #6A1B9A);\n"
                                       "}\n"
                                       "QPushButton:pressed {\n"
                                       "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                       "                                stop: 0 #6A1B9A, stop: 1 #4A148C);\n"
                                       "}")
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.frame)
        self.stackedWidget.addWidget(self.analysis_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        Platform.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Platform)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        Platform.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Platform)
        self.statusbar.setObjectName("statusbar")
        Platform.setStatusBar(self.statusbar)

        self.retranslateUi(Platform)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Platform)

    def retranslateUi(self, Platform):
        _translate = QtCore.QCoreApplication.translate
        Platform.setWindowTitle(_translate("Platform", "DataLite"))
        self.label.setText(
            _translate("Platform", "<h1 style=\'color: #ffffff\'> <b> DataLite <b> </h1>"))
        self.label_2.setText(_translate("Platform",
                                        "<div style=\'color: #ffffff; font-size: 14px; line-height: 1.5; margin: 20px; font-family: \"Segoe UI\", Arial, sans-serif;\'>\n"
                                        "    <!-- Заголовок -->\n"
                                        "    <div style=\"background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 15px; border-radius: 10px; margin-bottom: 20px;\">\n"
                                        "        <h2 style=\"color: #ffffff; font-size: 20px; font-weight: 600; margin: 0; text-align: center;\">\n"
                                        "            🚀 Профессиональная платформа аналитики\n"
                                        "        </h2>\n"
                                        "    </div>\n"
                                        "\n"
                                        "    <!-- Возможности системы -->\n"
                                        "    <div style=\"background: rgba(30, 58, 95, 0.9); padding: 20px; border-radius: 10px; margin-bottom: 15px; border-left: 4px solid #3182ce;\">\n"
                                        "        <h3 style=\"color: #90cdf4; font-size: 16px; font-weight: 600; margin: 0 0 15px 0; display: flex; align-items: center;\">\n"
                                        "            <span style=\"margin-right: 8px;\">📊</span>Возможности системы\n"
                                        "        </h3>\n"
                                        "\n"
                                        "        <div style=\"display: grid; gap: 10px;\">\n"
                                        "            <div style=\"display: flex; align-items: flex-start; gap: 10px;\">\n"
                                        "                <span style=\"color: #48bb78; font-size: 16px;\">📈</span>\n"
                                        "                <div>\n"
                                        "                    <div style=\"color: #bee3f8; font-weight: 600; font-size: 14px;\">Разведочный анализ (EDA)</div>\n"
                                        "                    <div style=\"color: #a0aec0; font-size: 12px;\">Исследование данных и выявление аномалий</div>\n"
                                        "                </div>\n"
                                        "            </div>\n"
                                        "\n"
                                        "            <div style=\"display: flex; align-items: flex-start; gap: 10px;\">\n"
                                        "                <span style=\"color: #4299e1; font-size: 16px;\">📊</span>\n"
                                        "                <div>\n"
                                        "                    <div style=\"color: #bee3f8; font-weight: 600; font-size: 14px;\">Визуализация данных</div>\n"
                                        "                    <div style=\"color: #a0aec0; font-size: 12px;\">Интерактивные дашборды и отчеты</div>\n"
                                        "                </div>\n"
                                        "            </div>\n"
                                        "\n"
                                        "            <div style=\"display: flex; align-items: flex-start; gap: 10px;\">\n"
                                        "                <span style=\"color: #ed8936; font-size: 16px;\">🔍</span>\n"
                                        "                <div>\n"
                                        "                    <div style=\"color: #bee3f8; font-weight: 600; font-size: 14px;\">ML моделирование</div>\n"
                                        "                    <div style=\"color: #a0aec0; font-size: 12px;\">Прогнозирование и анализ паттернов</div>\n"
                                        "                </div>\n"
                                        "            </div>\n"
                                        "\n"
                                        "            <div style=\"display: flex; align-items: flex-start; gap: 10px;\">\n"
                                        "                <span style=\"color: #9f7aea; font-size: 16px;\">📁</span>\n"
                                        "                <div>\n"
                                        "                    <div style=\"color: #bee3f8; font-weight: 600; font-size: 14px;\">Управление датасетами</div>\n"
                                        "                    <div style=\"color: #a0aec0; font-size: 12px;\">Хранение и каталогизация данных</div>\n"
                                        "                </div>\n"
                                        "            </div>\n"
                                        "        </div>\n"
                                        "    </div>\n"
                                        "    <br>\n"
                                        "    <!-- Форматы и Workflow в одной строке -->\n"
                                        "    <div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px;\">\n"
                                        "        <!-- Поддерживаемые форматы -->\n"
                                        "        <div style=\"background: rgba(30, 58, 95, 0.9); padding: 15px; border-radius: 10px; border-left: 4px solid #48bb78;\">\n"
                                        "            <h3 style=\"color: #90cdf4; font-size: 16px; font-weight: 600; margin: 0 0 12px 0; display: flex; align-items: center;\">\n"
                                        "                <span style=\"margin-right: 8px;\">📋</span>Форматы\n"
                                        "            </h3>\n"
                                        "\n"
                                        "            <div style=\"display: flex; flex-direction: column; gap: 8px;\">\n"
                                        "                <div style=\"display: flex; align-items: center; gap: 8px; padding: 8px; background: rgba(72, 187, 120, 0.1); border-radius: 6px;\">\n"
                                        "                    <span style=\"color: #68d391; font-size: 14px;\">📄</span>\n"
                                        "                    <span style=\"color: #bee3f8; font-weight: 600; font-size: 13px;\">CSV</span>\n"
                                        "                    <span style=\"color: #a0aec0; font-size: 12px; margin-left: auto;\">Табличные</span>\n"
                                        "                </div>\n"
                                        "\n"
                                        "                <div style=\"display: flex; align-items: center; gap: 8px; padding: 8px; background: rgba(66, 153, 225, 0.1); border-radius: 6px;\">\n"
                                        "                    <span style=\"color: #90cdf4; font-size: 14px;\">📑</span>\n"
                                        "                    <span style=\"color: #bee3f8; font-weight: 600; font-size: 13px;\">JSON</span>\n"
                                        "                    <span style=\"color: #a0aec0; font-size: 12px; margin-left: auto;\">Структурированные</span>\n"
                                        "                </div>\n"
                                        "            </div>\n"
                                        "        </div>\n"
                                        "    <br>\n"
                                        "\n"
                                        "        <!-- Workflow -->\n"
                                        "        <div style=\"background: linear-gradient(135deg, #2c5282 0%, #1a365d 100%); padding: 15px; border-radius: 10px;\">\n"
                                        "            <h3 style=\"color: #90cdf4; font-size: 16px; font-weight: 600; margin: 0 0 12px 0; display: flex; align-items: center;\">\n"
                                        "                <span style=\"margin-right: 8px;\">💡</span>Workflow\n"
                                        "            </h3>\n"
                                        "\n"
                                        "            <div style=\"display: flex; flex-direction: column; gap: 8px;\">\n"
                                        "                <div style=\"display: flex; align-items: center; gap: 8px;\">\n"
                                        "                    <div style=\"width: 20px; height: 20px; background: #3182ce; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; color: white; font-size: 11px;\">1</div>\n"
                                        "                    <div style=\"color: #bee3f8; font-size: 13px;\">Импорт данных</div>\n"
                                        "                </div>\n"
                                        "\n"
                                        "                <div style=\"display: flex; align-items: center; gap: 8px;\">\n"
                                        "                    <div style=\"width: 20px; height: 20px; background: #4299e1; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; color: white; font-size: 11px;\">2</div>\n"
                                        "                    <div style=\"color: #bee3f8; font-size: 13px;\">Выбор датасета</div>\n"
                                        "                </div>\n"
                                        "\n"
                                        "                <div style=\"display: flex; align-items: center; gap: 8px;\">\n"
                                        "                    <div style=\"width: 20px; height: 20px; background: #38b2ac; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; color: white; font-size: 11px;\">3</div>\n"
                                        "                    <div style=\"color: #bee3f8; font-size: 13px;\">Анализ данных</div>\n"
                                        "                </div>\n"
                                        "\n"
                                        "                <div style=\"display: flex; align-items: center; gap: 8px;\">\n"
                                        "                    <div style=\"width: 20px; height: 20px; background: #9f7aea; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; color: white; font-size: 11px;\">4</div>\n"
                                        "                    <div style=\"color: #bee3f8; font-size: 13px;\">Управление данными</div>\n"
                                        "                </div>\n"
                                        "            </div>\n"
                                        "        </div>\n"
                                        "    </div>\n"
                                        "</div>"))
        self.label_3.setText(_translate("Platform",
                                        "<h1 style=\'color: #1e3a5f; margin: 15px;\'> 🗂️ Управление датасетами <h1>"))
        self.stats_label.setText(_translate("Platform", "Загрузка..."))
        self.add_button.setText(_translate("Platform", "Добавить датасет"))
        self.open_button.setText(_translate("Platform", "Анализировать"))
        self.delete_button.setText(_translate("Platform", "Удалить"))
        self.update_button.setText(_translate("Platform", "Обновить"))
        self.label_4.setText(_translate("Platform",
                                        "<h1 style=\'color: #1e3a5f; margin: 15px; text-align: center;\'> 🔧 Инструменты анализа </h1>"))
        self.preprocessing_button.setText(_translate("Platform", "Предобработка данных"))
        self.visualization_button.setText(_translate("Platform", "Визуализация"))
        self.modeling_button.setText(_translate("Platform", "Моделирование"))
        self.back_button.setText(_translate("Platform", "Назад"))
