# Form implementation generated from reading ui file 'modeling_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModelingWindow(object):
    def setupUi(self, ModelingWindow):
        ModelingWindow.setObjectName("ModelingWindow")
        ModelingWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(parent=ModelingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.mainScrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.mainScrollArea.setWidgetResizable(True)
        self.mainScrollArea.setObjectName("mainScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.contentLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.contentLayout.setObjectName("contentLayout")
        self.leftPanel = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.leftPanel.setMinimumWidth(400)
        self.leftPanel.setMaximumWidth(450)
        self.leftPanel.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #e2e8f0;\n"
"}")
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setSpacing(10)
        self.leftLayout.setObjectName("leftLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.leftLayout.addWidget(self.titleLabel)
        self.modelLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.modelLabel.setObjectName("modelLabel")
        self.leftLayout.addWidget(self.modelLabel)
        self.modelComboBox = QtWidgets.QComboBox(parent=self.leftPanel)
        self.modelComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    color: #2d3748;\n"
"    min-height: 35px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #3182ce;\n"
"}")
        self.modelComboBox.setObjectName("modelComboBox")
        self.leftLayout.addWidget(self.modelComboBox)
        self.targetLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.targetLabel.setObjectName("targetLabel")
        self.leftLayout.addWidget(self.targetLabel)
        self.targetComboBox = QtWidgets.QComboBox(parent=self.leftPanel)
        self.targetComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"    color: #2d3748;\n"
"    min-height: 35px;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color: #3182ce;\n"
"}")
        self.targetComboBox.setObjectName("targetComboBox")
        self.leftLayout.addWidget(self.targetComboBox)
        self.featuresLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.featuresLabel.setObjectName("featuresLabel")
        self.leftLayout.addWidget(self.featuresLabel)
        self.featuresListWidget = QtWidgets.QListWidget(parent=self.leftPanel)
        self.featuresListWidget.setMinimumHeight(200)
        self.featuresListWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.featuresListWidget.setStyleSheet("QListWidget {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 8px 10px;\n"
"    border-bottom: 1px solid #edf2f7;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: #3182ce;\n"
"    color: white;\n"
"}")
        self.featuresListWidget.setObjectName("featuresListWidget")
        self.leftLayout.addWidget(self.featuresListWidget)
        self.paramsLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.paramsLabel.setObjectName("paramsLabel")
        self.leftLayout.addWidget(self.paramsLabel)
        self.testSizeLayout = QtWidgets.QHBoxLayout()
        self.testSizeLayout.setObjectName("testSizeLayout")
        self.testSizeLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.testSizeLabel.setStyleSheet("color: #4a5568;\n"
"font-size: 13px;\n"
"min-width: 120px;")
        self.testSizeLabel.setObjectName("testSizeLabel")
        self.testSizeLayout.addWidget(self.testSizeLabel)
        self.testSizeSpinBox = QtWidgets.QSpinBox(parent=self.leftPanel)
        self.testSizeSpinBox.setMinimum(10)
        self.testSizeSpinBox.setMaximum(50)
        self.testSizeSpinBox.setProperty("value", 15)
        self.testSizeSpinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"QSpinBox:hover {\n"
"    border-color: #3182ce;\n"
"}")
        self.testSizeSpinBox.setObjectName("testSizeSpinBox")
        self.testSizeLayout.addWidget(self.testSizeSpinBox)
        self.leftLayout.addLayout(self.testSizeLayout)
        self.seedLayout = QtWidgets.QHBoxLayout()
        self.seedLayout.setObjectName("seedLayout")
        self.seedLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.seedLabel.setStyleSheet("color: #4a5568;\n"
"font-size: 13px;\n"
"min-width: 120px;")
        self.seedLabel.setObjectName("seedLabel")
        self.seedLayout.addWidget(self.seedLabel)
        self.randomSeedSpinBox = QtWidgets.QSpinBox(parent=self.leftPanel)
        self.randomSeedSpinBox.setMinimum(0)
        self.randomSeedSpinBox.setMaximum(99999)
        self.randomSeedSpinBox.setProperty("value", 42)
        self.randomSeedSpinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"QSpinBox:hover {\n"
"    border-color: #3182ce;\n"
"}")
        self.randomSeedSpinBox.setObjectName("randomSeedSpinBox")
        self.seedLayout.addWidget(self.randomSeedSpinBox)
        self.leftLayout.addLayout(self.seedLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.leftLayout.addItem(spacerItem)
        self.showHeatmapButton = QtWidgets.QPushButton(parent=self.leftPanel)
        self.showHeatmapButton.setMinimumHeight(40)
        self.showHeatmapButton.setStyleSheet("QPushButton {\n"
"    background-color: #38a169;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2f855a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #276749;\n"
"}")
        self.showHeatmapButton.setObjectName("showHeatmapButton")
        self.leftLayout.addWidget(self.showHeatmapButton)
        self.buildModelButton = QtWidgets.QPushButton(parent=self.leftPanel)
        self.buildModelButton.setMinimumHeight(45)
        self.buildModelButton.setStyleSheet("QPushButton {\n"
"    background-color: #3182ce;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2c5282;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2a4365;\n"
"}")
        self.buildModelButton.setObjectName("buildModelButton")
        self.leftLayout.addWidget(self.buildModelButton)
        self.closeButton = QtWidgets.QPushButton(parent=self.leftPanel)
        self.closeButton.setMinimumHeight(35)
        self.closeButton.setStyleSheet("QPushButton {\n"
"    background-color: #718096;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4a5568;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2d3748;\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.leftLayout.addWidget(self.closeButton)
        self.contentLayout.addWidget(self.leftPanel)
        self.rightScrollArea = QtWidgets.QScrollArea(parent=self.scrollAreaWidgetContents)
        self.rightScrollArea.setWidgetResizable(True)
        self.rightScrollArea.setObjectName("rightScrollArea")
        self.rightScrollWidget = QtWidgets.QWidget()
        self.rightScrollWidget.setObjectName("rightScrollWidget")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightScrollWidget)
        self.rightLayout.setSpacing(15)
        self.rightLayout.setObjectName("rightLayout")
        self.resultsTitleLabel = QtWidgets.QLabel(parent=self.rightScrollWidget)
        self.resultsTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultsTitleLabel.setObjectName("resultsTitleLabel")
        self.rightLayout.addWidget(self.resultsTitleLabel)
        self.metricsFrame = QtWidgets.QFrame(parent=self.rightScrollWidget)
        self.metricsFrame.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #e2e8f0;\n"
"}")
        self.metricsFrame.setObjectName("metricsFrame")
        self.metricsLayout = QtWidgets.QVBoxLayout(self.metricsFrame)
        self.metricsLayout.setSpacing(8)
        self.metricsLayout.setObjectName("metricsLayout")
        self.metricsLabel = QtWidgets.QLabel(parent=self.metricsFrame)
        self.metricsLabel.setObjectName("metricsLabel")
        self.metricsLayout.addWidget(self.metricsLabel)
        self.metricsTextEdit = QtWidgets.QTextEdit(parent=self.metricsFrame)
        self.metricsTextEdit.setMinimumHeight(120)
        self.metricsTextEdit.setReadOnly(True)
        self.metricsTextEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    padding: 10px;\n"
"    font-size: 13px;\n"
"    color: #2d3748;\n"
"}")
        self.metricsTextEdit.setObjectName("metricsTextEdit")
        self.metricsLayout.addWidget(self.metricsTextEdit)
        self.rightLayout.addWidget(self.metricsFrame)
        self.predictionsFrame = QtWidgets.QFrame(parent=self.rightScrollWidget)
        self.predictionsFrame.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #e2e8f0;\n"
"}")
        self.predictionsFrame.setObjectName("predictionsFrame")
        self.predictionsLayout = QtWidgets.QVBoxLayout(self.predictionsFrame)
        self.predictionsLayout.setSpacing(8)
        self.predictionsLayout.setObjectName("predictionsLayout")
        self.predictionsLabel = QtWidgets.QLabel(parent=self.predictionsFrame)
        self.predictionsLabel.setObjectName("predictionsLabel")
        self.predictionsLayout.addWidget(self.predictionsLabel)
        self.predictionsTableView = QtWidgets.QTableView(parent=self.predictionsFrame)
        self.predictionsTableView.setMinimumHeight(250)
        self.predictionsTableView.setAlternatingRowColors(True)
        self.predictionsTableView.setStyleSheet("QTableView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #edf2f7;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    border-right: 1px solid #e2e8f0;\n"
"    border-bottom: 1px solid #3182ce;\n"
"    font-weight: bold;\n"
"    color: #2d3748;\n"
"}")
        self.predictionsTableView.setObjectName("predictionsTableView")
        self.predictionsLayout.addWidget(self.predictionsTableView)
        self.modelInfoLabel = QtWidgets.QLabel(parent=self.predictionsFrame)
        self.modelInfoLabel.setStyleSheet("color: #4a5568;\n"
"font-size: 12px;\n"
"padding: 8px;\n"
"background-color: #ebf8ff;\n"
"border-radius: 6px;\n"
"border-left: 4px solid #3182ce;")
        self.modelInfoLabel.setObjectName("modelInfoLabel")
        self.predictionsLayout.addWidget(self.modelInfoLabel)
        self.rightLayout.addWidget(self.predictionsFrame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightLayout.addItem(spacerItem1)
        self.rightScrollArea.setWidget(self.rightScrollWidget)
        self.contentLayout.addWidget(self.rightScrollArea)
        self.mainScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.mainScrollArea)
        ModelingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ModelingWindow)
        QtCore.QMetaObject.connectSlotsByName(ModelingWindow)

    def retranslateUi(self, ModelingWindow):
        _translate = QtCore.QCoreApplication.translate
        ModelingWindow.setWindowTitle(_translate("ModelingWindow", "Моделирование"))
        self.titleLabel.setText(_translate("ModelingWindow", "<h2 style=\'color: #1e3a5f; font-size: 18px; font-weight: bold; text-align: center; margin: 0; padding: 0;\'>Настройки моделирования</h2>"))
        self.modelLabel.setText(_translate("ModelingWindow", "<b style=\'color: #2d3748; font-size: 14px;\'>Выбор модели:</b>"))
        self.targetLabel.setText(_translate("ModelingWindow", "<b style=\'color: #2d3748; font-size: 14px;\'>Целевая переменная (таргет):</b>"))
        self.featuresLabel.setText(_translate("ModelingWindow", "<b style=\'color: #2d3748; font-size: 14px;\'>Признаки (фичи):</b>"))
        self.paramsLabel.setText(_translate("ModelingWindow", "<b style=\'color: #2d3748; font-size: 14px;\'>Параметры разбиения:</b>"))
        self.testSizeLabel.setText(_translate("ModelingWindow", "Тестовая выборка:"))
        self.testSizeSpinBox.setSuffix(_translate("ModelingWindow", "%"))
        self.seedLabel.setText(_translate("ModelingWindow", "Random seed:"))
        self.showHeatmapButton.setText(_translate("ModelingWindow", "Показать тепловую карту корреляций"))
        self.buildModelButton.setText(_translate("ModelingWindow", "Построить модель"))
        self.closeButton.setText(_translate("ModelingWindow", "Закрыть"))
        self.resultsTitleLabel.setText(_translate("ModelingWindow", "<h2 style=\'color: #1e3a5f; font-size: 18px; font-weight: bold; text-align: center; margin: 0; padding: 0;\'>Результаты моделирования</h2>"))
        self.metricsLabel.setText(_translate("ModelingWindow", "<b style=\'color: #2d3748; font-size: 14px;\'>Метрики модели:</b>"))
        self.metricsTextEdit.setHtml(_translate("ModelingWindow", "<div style=\'color: #718096; font-style: italic; text-align: center; padding: 20px;\'>\n"
"    Модель еще не построена. Нажмите кнопку \"Построить модель\" для получения результатов.\n"
"</div>"))
        self.predictionsLabel.setText(_translate("ModelingWindow", "<b style=\'color: #2d3748; font-size: 14px;\'>Сравнение предсказаний (первые 100 строк):</b>"))
        self.modelInfoLabel.setText(_translate("ModelingWindow", "Модель: Не построена | Целевая переменная: Не выбрана"))